/**
 * Generated wide views: one column per scalar fact and per segment, so dashboards
 * and ad hoc SQL read naturally. Regenerated by `pulse config apply` and after
 * every extract.
 */
import type { FactConfig, SegmentConfig } from '../config/schema.js';

export const RESERVED_COLUMNS = new Set(['user_id', 'username', 'display_name', 'profile_version_id', 'version_no', 'valid_from', 'valid_to', 'revision_created_at']);

const quote = (ident: string): string => `"${ident.replace(/"/g, '""')}"`;
const lit = (s: string): string => `'${s.replace(/'/g, "''")}'`;

function factColumn(f: FactConfig): string {
  const where = `FILTER (WHERE key = ${lit(f.key)} AND dim = '')`;
  switch (f.semantics) {
    case 'counter':
    case 'gauge':
      return `MAX(num) ${where} AS ${quote(f.key)}`;
    case 'boolean':
      return `BOOL_OR(bool) ${where} AS ${quote(f.key)}`;
    case 'timestamp':
      return `MAX(ts) ${where} AS ${quote(f.key)}`;
    default:
      return `MAX(text) ${where} AS ${quote(f.key)}`;
  }
}

function segmentColumn(s: SegmentConfig): string {
  const where = `FILTER (WHERE key = ${lit(s.key)})`;
  return s.label ? `MAX(label) ${where} AS ${quote(s.key)}` : `BOOL_OR(member) ${where} AS ${quote(s.key)}`;
}

/** SQL statements (in order) that (re)create the wide views for this config. */
export function wideViewSql(facts: FactConfig[], segments: SegmentConfig[] = []): string[] {
  const factCols = facts.filter((f) => f.shape === 'scalar').map(factColumn);
  const segCols = segments.map(segmentColumn);
  const select = ['pv.user_id', 'p.username', 'p.display_name', 'pv.id AS profile_version_id', 'pv.version_no', 'pv.valid_from', 'pv.valid_to', 'pv.revision_created_at'];
  const joins: string[] = ['LEFT JOIN player p ON p.user_id = pv.user_id'];
  if (factCols.length) {
    select.push(...facts.filter((f) => f.shape === 'scalar').map((f) => `f.${quote(f.key)}`));
    joins.push(`LEFT JOIN (SELECT profile_version_id,\n    ${factCols.join(',\n    ')}\n  FROM fact GROUP BY profile_version_id) f ON f.profile_version_id = pv.id`);
  }
  if (segCols.length) {
    select.push(...segments.map((s) => `s.${quote(s.key)}`));
    joins.push(
      `LEFT JOIN (SELECT profile_version_id,\n    ${segCols.join(',\n    ')}\n  FROM segment_membership GROUP BY profile_version_id) s ON s.profile_version_id = pv.id`,
    );
  }
  const history = ['CREATE VIEW v_player_history AS', `SELECT ${select.join(',\n       ')}`, 'FROM profile_version pv', ...joins].join('\n');
  return [
    'DROP VIEW IF EXISTS v_player_current',
    'DROP VIEW IF EXISTS v_player_history',
    history,
    'CREATE VIEW v_player_current AS SELECT * FROM v_player_history WHERE valid_to IS NULL',
  ];
}
